### ISSUE TITLE
avahi-alias-remove does not remove alias from /etc/avahi/aliases

### ISSUE THREAD

**Issue by thoschworks** [piku/avahi-aliases#2]
`avahi-alias-remove` does not remove alias from `/etc/avahi/aliases`:

```
thosch@testbed:~/avahi-aliases-master $ cat /etc/avahi/aliases
testhost.local
thosch@testbed:~/avahi-aliases-master $ sudo avahi-add-alias doodle.local
looking for [doodle.local] to match [testhost.local]
doodle.local : added
kill 4717
kill 4718
publishing << doodle.local >>
publishing << testhost.local >>
done
thosch@testbed:~/avahi-aliases-master $ cat /etc/avahi/aliases
testhost.local
doodle.local
thosch@testbed:~/avahi-aliases-master $ sudo avahi-remove-alias doodle.local
kill 4861
kill 4862
publishing << doodle.local >>
publishing << testhost.local >>
done
thosch@testbed:~/avahi-aliases-master $ cat /etc/avahi/aliases
testhost.local
doodle.local
thosch@testbed:~/avahi-aliases-master $
```

**Comment by emaiax** [comment]
@thoschworks my PR fixes this issue. Thank you!

**Comment by thoschworks** [comment]
@emaiax Thanks for your work. :+1:

Which of your commits is fixing this problem? (I am asking for learning purposes...)

BTW: Did you see my comment on the formating commit?

It would be nice, if @rcarmo or @piku would merge your PR...

Or I have to switch to your fork.

**Comment by rcarmo** [comment]
It's merged now. I need to get better e-mail filters and set up notifications differently...

**Comment by emaiax** [comment]
@thoschworks this commit https://github.com/piku/avahi-aliases/pull/3/commits/3a1cb0bf07c62e989fdab8601daffa50b5c7158b fixes this issue. :)
